image: node:16.16.0

# before_script:
#   - npm install hexo-cli -g
#   - npm install

pages:
  cache:
    paths:
      - node_modules/
      - dist
  script:
    - yarn install
    - yarn build
  artifacts:
    paths:
      - public

  only:
    - master

  # rules:
  #   - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
